// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gizfniqgiemjyifrgojq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpemZuaXFnaWVtanlpZnJnb2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MTUxOTQsImV4cCI6MjA1MDI5MTE5NH0.snjRAZT3wL8BgPoZ1n1wWyfuReosLmJpesVs1gaFBKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);